/**
 * Bootstrap rents.seed.json + postal-areas.ts from StatFin asvu 13eb.
 *
 * One-shot generator. Run with:
 *   node --experimental-strip-types scripts/build-rents-seed.mts
 *
 * Output:
 *   src/lib/server/rents.seed.json  (RentCell map keyed by `${pc}_${room}`)
 *   src/lib/server/postal-areas.ts  (postalToTown + postalToMk lookups)
 */
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { fetchRentsMeta, fetchRents } from '../src/lib/server/statfin-rents.ts';
import type { RentCell } from '../src/lib/server/rents.ts';

const TABLE_URL =
	'https://pxdata.stat.fi/PxWeb/api/v1/en/StatFin_Passiivi/asvu/statfinpas_asvu_pxt_13eb_2025q4.px';

async function main() {
	const { quarters, postalCodes } = await fetchRentsMeta();
	const wantedQuarters = quarters.slice(-4);

	const metaRes = await fetch(TABLE_URL);
	const meta = (await metaRes.json()) as {
		variables: { code: string; values: string[]; valueTexts: string[] }[];
	};
	const pcDim = meta.variables.find((v) => v.code === 'Postinumero');
	if (!pcDim) throw new Error('Postinumero dim missing');

	// valueText format: "00100 Helsinki Keskusta - Etu-Töölö   (Helsinki )"
	const pcToTown = new Map<string, string>();
	const pcToMk = new Map<string, string>();
	for (let i = 0; i < pcDim.values.length; i++) {
		const pc = pcDim.values[i];
		const txt = pcDim.valueTexts[i] ?? '';
		const m = txt.match(/\(([^)]+)\)/g);
		if (!m || m.length < 1) continue;
		const town = m[0].replace(/[()]/g, '').trim();
		const mk = (m[1] ?? m[0]).replace(/[()]/g, '').trim();
		if (town) pcToTown.set(pc, town);
		if (mk) pcToMk.set(pc, mk);
	}
	console.log(
		`[build-rents-seed] mappings: ${pcToTown.size} postal -> ${new Set(pcToTown.values()).size} towns`
	);

	console.log(
		`[build-rents-seed] quarters=${wantedQuarters.join(',')} postalCodes=${postalCodes.length}`
	);
	const cells = await fetchRents({
		quarters: wantedQuarters,
		postalCodes
	});

	const out: Record<string, RentCell> = {};
	let suppressed = 0;
	let populated = 0;
	for (const [k, v] of Object.entries(cells)) {
		out[k] = v;
		if (v.benchmark_eur_m2_kk === null) suppressed++;
		else populated++;
	}

	// Synthesize town-level fall-back cells so the engine's tier chain works
	// when the postal cell is suppressed. Aggregate by town: transaction-weighted
	// EUR/m² across populated postal cells in that town, summed n, union of series.
	const townAgg = new Map<
		string,
		{ num: number; den: number; n: number; seriesMap: Map<string, { num: number; den: number; n: number }> }
	>();
	for (const [key, v] of Object.entries(cells)) {
		if (v.benchmark_eur_m2_kk === null) continue;
		const pc = key.split('_')[0];
		const town = pcToTown.get(pc);
		if (!town) continue;
		const room = key.split('_')[1];
		const k = `${town}_${room}`;
		if (!townAgg.has(k)) townAgg.set(k, { num: 0, den: 0, n: 0, seriesMap: new Map() });
		const a = townAgg.get(k)!;
		a.num += v.benchmark_eur_m2_kk * v.n_4q;
		a.den += v.n_4q;
		a.n += v.n_4q;
		for (const s of v.series) {
			if (s.eur_m2 === null || s.n === null) continue;
			const ek = s.q;
			if (!a.seriesMap.has(ek)) a.seriesMap.set(ek, { num: 0, den: 0, n: 0 });
			const e = a.seriesMap.get(ek)!;
			e.num += s.eur_m2 * s.n;
			e.den += s.n;
			e.n += s.n;
		}
	}
	let townsAdded = 0;
	for (const [k, a] of townAgg) {
		if (a.den === 0) continue;
		const eurM2 = a.num / a.den;
		const series = wantedQuarters.map((q) => {
			const e = a.seriesMap.get(q);
			return e && e.den > 0
				? { q, eur_m2: e.num / e.den, n: e.n }
				: { q, eur_m2: null, n: null };
		});
		out[k] = {
			benchmark_eur_m2_kk: eurM2,
			n_4q: a.n,
			latest_quarter: [...series].reverse().find((s) => s.eur_m2 !== null)?.q ?? null,
			series
		};
		townsAdded++;
	}
	console.log(`[build-rents-seed] synthesized ${townsAdded} town-level cells`);

	const here = fileURLToPath(new URL('.', import.meta.url));
	const seedPath = resolve(here, '..', 'src', 'lib', 'server', 'rents.seed.json');
	writeFileSync(seedPath, JSON.stringify(out, null, '\t') + '\n', 'utf8');
	console.log(
		`[build-rents-seed] wrote ${Object.keys(out).length} cells (${populated} populated, ${suppressed} suppressed) -> ${seedPath}`
	);

	const postcodeHeader = `// AUTO-GENERATED by scripts/build-rents-seed.mts — do not edit by hand.\n`;
	const tsBody =
		postcodeHeader +
		`const TOWN = ${JSON.stringify(Object.fromEntries(pcToTown), null, '\t')} as Record<string, string>;\n` +
		`const MK = ${JSON.stringify(Object.fromEntries(pcToMk), null, '\t')} as Record<string, string>;\n` +
		`\n` +
		`export function postalToTown(pc: string): string | null {\n` +
		`\treturn TOWN[pc] ?? null;\n` +
		`}\n` +
		`\n` +
		`export function postalToMk(pc: string): string | null {\n` +
		`\treturn MK[pc] ?? null;\n` +
		`}\n` +
		`\n` +
		`/** Postal codes that have at least one populated cell in rents.seed.json. */\n` +
		`export const KNOWN_POSTAL_CODES: string[] = ${JSON.stringify([...pcToTown.keys()].sort())};\n`;
	const tsPath = resolve(here, '..', 'src', 'lib', 'server', 'postal-areas.ts');
	writeFileSync(tsPath, tsBody, 'utf8');
	console.log(`[build-rents-seed] wrote ${tsPath}`);
}

main().catch((e) => {
	console.error(e);
	process.exit(1);
});